name: humlab-westac
channels:
- conda-forge
- defaults
dependencies:
- alive-progress ==1.*,>=1.6.1
- attrs
- black
- bokeh
- click
- colorcet
- coverage
- cython
- cytoolz
- debugpy ==1.*,>=1.2.1
- decorator
- flake8
- flake8-black
- ftfy
- gensim
- holoviews
- humanfriendly
- invoke
- ipycytoscape # ==1.1.0
- ipyfilechooser ==0.*,>=0.4.0
- ipykernel
- ipympl
- ipywidgets # ==7.5.1
- isort ==5.*,>=5.5.4
- joblib
- jupyterlab ==2.2.9
- jupytext
- lxml
- markdown
- matplotlib
- matplotlib-venn ==0.*,>=0.11.6
- memoization
- more-itertools
- mypy ==0.*,>=0.782.0
- nbstripout
- networkx
- nltk
- numpy
- openpyxl
- pandas
- pep8-naming ==0.*,>=0.11.1
- pre-commit
- py4j
- pycodestyle ==2.*,>=2.6.0
- pydotplus
- pyemd
- pyflakes ==2.*,>=2.2.0
- pylint
- pytest
- pytest-cov ==2.*,>=2.10.1
- python-dotenv
- python-louvain
- qgrid ==1.*,>=1.3.1
- rope
- scattertext
- scikit-learn
- scipy
- seaborn
- spacy ==2.3.2
- statsmodels
- textacy
- tqdm
- traitlets
- wordcloud
- xlrd
- xmltodict
- yapf ==0.*,>=0.30.0
- pip
- pip:
  - appnope
  - cutter-ng
  - dephell
  - flake8-pytest-style
  - humlab-penelope
  - ipyaggrid
  - jupyter-bokeh
  - pandas-bokeh
  - sklearn