### Type:
GET {{protocol}}://{{host}}/dark-29967/
Authorization: Basic {{user}}:{{password}}
content-type: application/json
mode: cors


### Type:
GET {{protocol}}://{{host}}/dark-29967/
Authorization: Basic {{user}}:{{password}}
content-type: application/json
mode: cors