corpus_name: parliamentary-debates-protocol
corpus_pattern: '*.zip'
corpus_type: 3
language: swedish
checkpoint_opts:
    content_type_code: 1
    sep: "\t"
    quoting: 3
    document_index_name: document_index.csv
    document_index_sep: "\t"
    text_column: text
    lemma_column: lemma
    pos_column: pos
    custom_serializer_classname: westac.riksdagens_protokoll.parlaclarin.ParlaCsvContentSerializer
    index_column: null
pipelines:
  tagged_frame_pipeline: westac.riksdagens_protokoll.parlaclarin.load_tagged_frame_pipeline
pipeline_payload:
  source:
  document_index_source: null
  document_index_sep: "\t"
  filenames: null
  memory_store:
    lang: se
    tagger: Stanza
    text_column: text
    lemma_column: lemma
    pos_column: pos
  pos_schema_name: Universal
text_reader_opts:
  as_binary: false
  filename_fields:
   - "year:prot\\_(\\d{4}).*"
   - "year2:prot_\\d{4}(\\d{2})__*"
   - "number:prot_\\d+[afk_]{0,4}__(\\d+)@\\d+.*"
   - "speech_index:prot_\\d+[afk_]{0,4}__\\d+@(\\d+).*"
  filename_filter: null
  filename_pattern: '*.csv'
  index_field: null
  sep: "\t"
  quoting: 3
